#' Rebuild an inbox contribution in the private review queue
#' @param fields Named list of fields received through the configured submission
#'   inbox. Untrusted metadata are re-fetched from Zenodo; links are not followed
#'   unless they exactly match a file in that record.
#' @param queue Administrator-controlled persistent private queue directory.
#' @return Pending proposal ID. Repeated imports are deduplicated. No approval
#'   or publication is performed.
#' @details This maintainer operation supports the link-only Formspree fields
#'   generated by ALS Downloader. It retrieves Zenodo metadata and, for polygon
#'   coverage, one bounded boundary file. It never downloads point clouds.
#'   Access to the inbox is configured separately; no inbox API key is bundled.
#' @export
import_zenodo_inbox <- function(fields, queue) {
  if (!is.list(fields) || is.null(names(fields)) || anyDuplicated(names(fields)))
    stop("Inbox fields must be a uniquely named list.")
  field <- function(name, required = FALSE, limit = 2000L) {
    value <- fields[[name]]
    if (is.null(value) && !required) return("")
    if (!is.character(value) || length(value) != 1L || is.na(value) ||
        nchar(value, type = "bytes") > limit || (required && !nzchar(trimws(value))))
      stop(paste("Invalid inbox field:", name))
    value
  }
  id <- zenodo_record_id(field("doi", TRUE))
  record <- field("record")
  if (nzchar(record) && !identical(zenodo_record_id(record), id))
    stop("Inbox record and DOI disagree.")
  keys <- strsplit(field("files", TRUE, 500000L), "\n", fixed = TRUE)[[1]]
  if (length(keys) > 2000L || any(!nzchar(keys)) || anyDuplicated(keys))
    stop("Invalid inbox file selection.")
  meta <- inspect_zenodo(id)
  if (!all(keys %in% vapply(meta$files, `[[`, "", "key")))
    stop("Inbox files are not present in the current Zenodo record.")
  boundary_url <- field("boundary")
  if (nzchar(boundary_url)) {
    names <- vapply(meta$files, `[[`, "", "key")
    urls <- paste0("https://zenodo.org/records/", id, "/files/",
      vapply(names, utils::URLencode, "", reserved = TRUE))
    match <- match(boundary_url, urls)
    if (is.na(match)) stop("Inbox boundary must be an exact file link in this Zenodo record.")
    path <- zenodo_boundary_download(meta, names[match])
    on.exit(unlink(path), add = TRUE)
    mapping <- field("file_mapping")
    boundary <- if (!nzchar(mapping) || identical(mapping, "Use the boundary file_key column."))
      zenodo_boundary(path) else zenodo_map_boundary(path, mapping)
  } else {
    number <- function(name) {
      value <- suppressWarnings(as.numeric(field(name, TRUE)))
      if (!is.finite(value)) stop(paste("Invalid inbox coordinate or distance:", name))
      value
    }
    boundary <- zenodo_square(number("centre_longitude"), number("centre_latitude"),
      number("centre_to_side_metres"), keys)
  }
  proposal <- zenodo_build(meta, boundary, field("acquisition"), field("platform", TRUE), field("email"))
  mapped <- vapply(proposal$index$features, function(f) f$properties$file_key, "")
  if (!setequal(mapped, keys)) stop("Inbox file selection does not match the coverage mapping.")
  reference <- field("reference")
  if (nzchar(reference) && !identical(reference, proposal$id))
    stop("Inbox proposal changed since submission; request a new validated proposal.")
  submit_zenodo(proposal, queue)
}
